## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

## ~~~~~ sample sheet ~~~~~
### See `example_sample_sheet.csv` for details
# SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/visium/CS001-5.csv
# SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/visium/vy3.csv
# SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/visium/vy3D.csv
SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/seeker/SHVN_1_2-NYGC.csv

# Resource parameters
CORES: 16               # how many cores to give each process
MEMLIMIT: 128000000000  # limit in bytes
MEMLIMIT_MB: 128000     # limit in megabytes
MEMLIMIT_GB: 128G       # mem limit for kallisto

# Recipe details (whitelists, barcode/UMI design, etc.)
RECIPE_SHEET: resources/recipe_sheet.csv

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: tmp
OUTDIR: out

########################################################################################################
# Executables - file paths
########################################################################################################
EXEC:
  BLASTN: blastn
  BWA: bwa-mem2
  BOWTIE2: bowtie2
  BUSTOOLS: bustools 
  CUTADAPT: cutadapt 
  FASTQC: fastqc 
  FASTX_COLLAPSER: fastx_collapser
  K8: scripts/k8-0.2.4/k8-Linux
  KALLISTO: kallisto
  KB: kb
  MIRGE: miRge3.0
  MINIMAP2: minimap2
  PIGZ: pigz
  QUALIMAP: qualimap
  SAMTOOLS: samtools
  SEQTK: seqtk
  STAR: STAR 
  UMITOOLS: umi_tools
  VSEARCH: vsearch

########################################################################################################
# Resources - file paths
########################################################################################################
FASTQC_ADAPTERS: resources/fastqc_adapters.txt 
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
MIRGE_LIB: resources/miRge3_Lib

########################################################################################################
# Library details
########################################################################################################
R1_INTERNAL_ADAPTER: "TCTTCAGCGTTCCCGAGA" # internal R1 adapter between slideseq barcodes
R1_PRIMER: "CTACACGACGCTCTTCCGATCT" # R1 primer (used in VIsium & Seeker)

piRNA_INDEX: '/path/to/genomes/pirbase/mmu/gold/bowtie2/index' # bowtie2 index of piRNAs; just mouse implemented now...
MAX_SHORT_READ_LENGTH: 34 # max read length for reads to be aligned to short RNA references


########################################################################################################
# ONT options
########################################################################################################
READ_STRUCTURE_BATCH_SIZE: 40000
READ_STRUCTURE_FLAGS: ""

MM2_REF: "/gpfs/commons/groups/innovation/dwm/ref_snake/out/mus_musculus/genome/minimap2"
REF_GENOME_FASTA: "/gpfs/commons/groups/innovation/dwm/ref_snake/out/mus_musculus/genome/raw/genome.fa"
REF_CHROM_SIZES: "/gpfs/commons/groups/innovation/dwm/ref_snake/out/mus_musculus/genome/raw/chrom_sizes.tsv"
REF_GENES_BED: "/gpfs/commons/groups/innovation/dwm/ref_snake/out/mus_musculus/genome/raw/annotations.bed"

RESOURCES_MM2_MEM_GB: 6
RESOURCES_MM2_MAX_THREADS: 12
RESOURCES_MM2_FLAGS: "-I 4G"

BARCODE_ADAPTER1_SUFF_LENGTH: 10
BARCODE_MIN_QUALITY: 12
BARCODE_MAX_ED: 4
BARCODE_MIN_ED_DIFF: 2